"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['llama.py']
DATA_FILES = ['server.py', 'server', 'llama', 'llama-2-13b-chat.ggmlv3.q4_0.bin']
OPTIONS = {
    'packages' : ['flask', 'requests', 'chardet', 'waitress'],
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
